/**
 * Search catalog: links from all 4 pages for the Search bar.
 * - Knowledge Center (this site)
 * - New Hire Homepage
 * - Leader Resource Center
 * - Performance Support
 *
 * Each link: { text: "Link label", href: "https://..." }
 * For copy-to-clipboard links use: { text: "Label", href: "#", dataCopy: "path" }
 */
const SEARCH_PAGES = [
  {
    id: "knowledge-center",
    title: "Knowledge Center",
    links: [
      { text: "CTU Admissions Call Script", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/CTU%20Admissions%20Scripts/Call%20-%20GEN%20MIL%20EAC%20NUR.aspx" },
      { text: "CTU Re-Entry Admissions Call Script", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/CTU%20Admissions%20Scripts/Reentry%20Script%20(LT365%20and%20GT365).aspx" },
      { text: "CTUO Doctoral Admissions Call Script", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/CTU%20Admissions%20Scripts/Doctoral%20Admissions%20Interview%20Guide.aspx" },
      { text: "CD Admissions Call Script", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Coding%20Dojo%20Resources/Admissions%20Scripts/Coding%20Dojo%20Admissions%20Interview%20Script.pdf" },
      { text: "CTU Appointment Script", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Scripts%20%20Supplemental/Appointment%20Guide%20-%20In%20the%20Interview.aspx" },
      { text: "CTU CI - App Due Follow Up Call", href: "file:///S:/CTU%20Admissions/Test%20Sites/CI%20Script%20-%20Test%20Site/Individual%20Test%20Sites/Aleks%20-%20CI%20Script%20-%20Test%20Site/index.html" },
      { text: "Potential Fraud Talking Points", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Live%20Chat%20Interviews%20CTU24.pdf" },
      { text: "PILOT Admissions Call", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/CTU%20Admissions%20Scripts/Pilot%20Script.aspx" },
      { text: "CTU Welcome Call", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Scripts%20%20Student%20Prep/NSWC_FAFSA_Completed_Online-Admissions.aspx" },
      { text: "CTU Welcome Call Follow Up", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Scripts%20%20Student%20Prep/Welcome%20Call%20Follow%20Up%20-%20Online%20Admissions.aspx" },
      { text: "CTUO Orientation Call", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Scripts%20%20Student%20Prep/Orientation%20Call%20-%20Online%20Admissions.aspx" },
      { text: "CTU Enter Class Call", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Scripts%20%20Student%20Prep/Enter%20Class%20Call.aspx" },
      { text: "CTU Start Week Script", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Scripts%20%20Student%20Prep/Start%20Week.aspx" },
      { text: "CTU Handoff Call", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Scripts%20%20Student%20Prep/Start%20Week%20Handoff.aspx" },
      { text: "CD Welcome Call", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Coding%20Dojo%20Resources/Dojo%20Student%20Prep%20Scripts/CD%20Welcome%20Call%20Script%20Final.pdf" },
      { text: "CD Welcome Call Follow Up", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Coding%20Dojo%20Resources/Dojo%20Student%20Prep%20Scripts/CD%20Welcome%20Call%20Follow%20Up%20Script%20Final.pdf" },
      { text: "CD Orientation Call", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Coding%20Dojo%20Resources/Dojo%20Student%20Prep%20Scripts/CD%20Orientation%20Call%20Script%20Final.pdf" },
      { text: "CD Enter Class Call", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Coding%20Dojo%20Resources/Dojo%20Student%20Prep%20Scripts/CD%20Enter%20Class%20Call%20Script%20Final.pdf" },
      { text: "CD Start Week Script", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Coding%20Dojo%20Resources/Dojo%20Student%20Prep%20Scripts/CD%20Start%20Week%20Script%20Final%20Pending%20Comment.pdf" },
      { text: "CD Handoff Call", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Coding%20Dojo%20Resources/Dojo%20Student%20Prep%20Scripts/CD%20Handoff%20Call%20Final.pdf" },
      { text: "Student Prep Call & Documentation Guidelines", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/Admissions%20Forms/Performance%20Support%20Documents/Student%20Prep%20Call%20Guide.pdf" },
      { text: "Admissions Rules of the Road", href: "https://livecareered.sharepoint.com/sites/ConnectEd/ethics-compliance/Policy%20Resources/Forms/AllItems.aspx?viewid=5f934a8a%2Da967%2D4737%2Da30d%2D48628ad9753f&viewpath=%2Fsites%2FConnectEd%2Fethics%2Dcompliance%2FPolicy%20Resources%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FConnectEd%2Fethics%2Dcompliance%2FPolicy%20Resources%2FAdmission%2FCTU%5FDojo%20Admissions%20Rules%20of%20the%20Road%2Epdf&parent=%2Fsites%2FConnectEd%2Fethics%2Dcompliance%2FPolicy%20Resources%2FAdmission" },
      { text: "Admissions Student Communication Guidelines", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Written%20Student%20Communication%20Guidelines.pdf" },
      { text: "Admissions Student Cancellation Policy", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Admissions%20Student%20Cancellation%20Policy.pdf" },
      { text: "Phone Number Mask Talking Points", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/Admissions%20Forms/Phone%20Number%20Mask%20Talking%20Points.pdf" },
      { text: "DNC | Not Interested | EWC Policy Guide", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/DNC_NI_EWC%20Guidebook%20FINAL.pdf" },
      { text: "Virtual Campus & Mobile App Guide", href: "https://share.articulate.com/LUivViGeWwqNsC-kExFKb" },
      { text: "Unacceptable Schools List", href: "https://livecareered.sharepoint.com/sites/ConnectEd/academics/pog/default.aspx" },
      { text: "Admissions Code of Conduct SOP", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Admissions%20Code%20of%20Conduct%20SOP.pdf" },
      { text: "Student Recording of Interview", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/COS%20AUR%20Materials/Student%20Recording%20of%20Admissions%20Interview%20(Ground).pdf" },
      { text: "CTU Admissions FAQ", href: "file:///S:/CTU%20Admissions/Test%20Sites/FAQ%20-%20Test%20Site/Individual%20Test%20Sites/Aleks%20-%20FAQ%20-%20Test%20Site/index.html" },
      { text: "CTU University Catalog", href: "https://coloradotech.smartcatalogiq.com/en/2026/catalog" },
      { text: "CTU Campus Presentation", href: "https://presentation.coloradotech.edu/" },
      { text: "CTU CCE Resource Center", href: "https://eac1.my.site.com/CCEResource/s/login/?ec=302&startURL=%2FCCEResource%2Fs%2F" },
      { text: "COS Campus Tour Job Aid", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/Admissions%20Forms/COS%20AUR%20Materials/COS%20Campus%20Tour%20Job%20Aid.pdf" },
      { text: "FSA ID Job Aid", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/Admissions%20Forms/FAFSA%20Scripts/FSA%20ID%20Guide.pdf" },
      { text: "FAFSA Guide", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Admissions Guidebooks/FAFSA_Guide/index.aspx" },
      { text: "FAFSA FAQs", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/FAFSA%20Comprehensive%20FAQ/FAFSA%20FAQ%20Advisor.aspx" },
      { text: "CTU Application Demo Student", href: "https://enrollment.coloradotech.edu/#/LandingPage" },
      { text: "CD Application Demo Login", href: "https://codingdojo-enrollment.coloradotech.edu/#/LandingPage" },
      { text: "CD Admissions Talking Points", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Coding%20Dojo%20Resources/Dojo%20KC%20Resources/CD%20Admissions%20FAQs%20(student-facing).pdf" },
      { text: "CD Student Catalog", href: "https://coloradotech.smartcatalogiq.com/en/current/catalog/copy-of-general-information-on-coding-dojo-certificate-programs/" },
      { text: "CTUO Intranet", href: "http://ctuintranet/" },
      { text: "COS Intranet", href: "http://cecintranet/ChooseCampus.aspx?url=http://cecintranet/ChooseCampus.aspx?url=http://cecintranet/" },
      { text: "CD Intranet", href: "http://codingdojo-intranet" },
      { text: "ADM COS", href: "https://csstaff.coloradotech.edu" },
      { text: "ADM DEN", href: "https://denverstaff.coloradotech.edu/mycampus/index.aspx" },
      { text: "Admin Website", href: "file:///S:/CTU%20Online/CTU%20Admissions/Administration/Administrative%20Assistants/Admissions%20Website/CTUO%20Admissions%20Website.htm" },
      { text: "IEX Advisor", href: "https://perdoceo.nicecloudsvc.com/wfm" },
      { text: "ClearSlide", href: "https://www.clearslide.com/auth/login" },
      { text: "CTU CampusVue", href: "https://anthology.perdoceoed.com/RDWeb/Pages/en-US/login.aspx?ReturnUrl=/RDWeb/Pages/en-US/Default.aspx" },
      { text: "CD CampusVue", href: "https://campusnexus.careered.com/" }
    ]
  },
  {
    id: "performance-support",
    title: "Performance Support",
    links: [
      { text: "CTU Commitment Grant Quick Reference Guide", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/CTU%20Commitment%20Grant%20One%20Pager.pdf" },
      { text: "CTU Features Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/CTU%20Features%20Job%20Aid%20v1.0.pdf" },
      { text: "CTU Referrals and PDIs Key Points", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Referrals%20and%20PDIs.pdf" },
      { text: "CTU Interview Effectiveness Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Interview%20Effectiveness%20Job%20Aid.pdf" },
      { text: "CTU Cancel Student Interview Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Online%20Advisor%20Performance%20Support%20Documents/REQ2057235%20Cancel%20Student%20Interview%20Job%20Aid.pdf" },
      { text: "CTUO Researching a Student Record: ReEntry Admissions", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Researching%20a%20ReEntry%20Student%20Record_Final.pdf" },
      { text: "Personalize the Feature, Ask the Benefit (PFAB) - Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/CTU%20PFAB_Job_Aid.pdf" },
      { text: "CTU ClearSlide Admissions Guide", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/ClearSlide%20Admissions%20Guide.pdf" },
      { text: "CTU How to Access the CTU Mobile Demo Job Aid", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/CTU%20Mobile%20How%20to%20Access%20Demo.pdf" },
      { text: "CTU Live Chat Lifecycle", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Live_Chat_Interaction_Flow.pdf" },
      { text: "CTU SMS Response Management SOP", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/SOP%20for%20SMS%20Response%20Management.pdf" },
      { text: "CTUO Intranet Guide", href: "https://share.articulate.com/PDzHhCt17-2D0GSI2qdeB" },
      { text: "CTUO Reinstating a POG Cancel SOP", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/SOP%20for%20Reinstating%20True%20POG%20Cancels.pdf" },
      { text: "COS Admissions Desktop Management Guidebook", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/GRD%20ADM%20Guidebook.pdf" },
      { text: "COS ADM Disposition Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/ADM%20Disposition%20Job%20Aid_FNL.pdf" },
      { text: "CD Intranet Guide", href: "https://share.articulate.com/9tUU9Pi_-HZuwIfM7Y9E-" },
      { text: "CTUO/CD IMS Disposition Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/CTU%20Intranet%20Statusing%20Job%20Aid%20(Online).pdf" },
      { text: "Mapping Network Drives | I, S, & G Drives", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Mapping_Job_Aid.pdf" },
      { text: "Messenger Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Messenger%20Job%20Aid%20CM.pdf" },
      { text: "Microsoft Outlook Email & Calendar Basics Guide", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Outlook%20Guide_Final.pdf" },
      { text: "Supplemental Trainings & eLearn Modules", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/Supplemental%20Trainings%20%20eLearn%20Modules.pdf" },
      { text: "CTU BSCE FAQs", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/BSCE%20FAQs.pdf" },
      { text: "CTU BSPSYCH v. BSCJ-HS Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/BS%20Psych%20V%20BSCJ.pdf" },
      { text: "CTU BSCE v. BSCS v. BSIT Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/BSCE%20v.%20BSCS%20v.%20BSIT%20Job%20Aid.pdf" },
      { text: "CTU Exploring Healthcare Management Degrees - Job Aid", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/Exploring%20CTU%20BSHCM%20-%20Job%20Aid.pdf" },
      { text: "CTU University Basics", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/CTU%20University%20Basics.pdf" },
      { text: "CTU Admissions Glossary of Terms", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Glossaries/General/v3-4/interaction_html5.aspx" },
      { text: "CTUO BSN FAQs", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/training/Product%20Knowledge/Bachelor%20of%20Science%20in%20Nursing%20(BSN)%20-%20FAQ.pdf" },
      { text: "CTUO MSN FAQs", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/FAQs%20-%20MSN.pdf" },
      { text: "CTUO DNP FAQs", href: "https://livecareered.sharepoint.com/sites/ctu/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/FAQs%20-%20DNP_vfinal_v2.pdf" },
      { text: "CTUO University Badges for Non-Degree Seeking Students", href: "https://careered.libguides.com/CTUBadgeCriteria" },
      { text: "COS BSEE FAQs", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Program%20and%20Product%20Knowledge/FAQs%20BS%20in%20Electrical%20Engineering.pdf" },
      { text: "CD Glossary of Terms", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/CD%20Glossary%20of%20Terms_Final.pdf" },
      { text: "CTU Military Admissions Guide", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Military%20Admissions%20Guide.pdf" },
      { text: "CTU Problem Solving Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Problem_Solving_Job_Aid.pdf" },
      { text: "CTU Alumni Access FAQs", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Alumni%20Access%20FAQ%20Sheet.pdf" },
      { text: "CTUO Financial Aid Packaging Steps", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Financial%20Aid%20Packaging%20Stages.pdf" },
      { text: "CTUO Student Prep Tracker", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Student%20Prep%20Tracker.xlsx" },
      { text: "COS Financial Aid Packaging Steps", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/COS_Denver%20Financial%20Aid%20Packaging%20Steps.pdf" },
      { text: "CD Student Prep Tracker", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Coding%20Dojo%20Student%20Prep%20Tracker%20Final.xlsx" },
      { text: "CD Problem Solving Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/CD_Problem%20Solving%20Job%20Aid.pdf" },
      { text: "CD Finance Packaging Steps Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/CD%20Finance%20Packaging%20Steps%20Final.pdf" },
      { text: "Activities for Enrolled Students", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Activities%20for%20Enrolled%20Students.pdf" },
      { text: "Student Progression", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Student%20Progression.pdf" },
      { text: "CTU Criminal Background Check SOP", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/COS_DEN%20Background%20Check_Final.pdf" },
      { text: "CTUO Multiple Concentrations APC Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Multiple_Concentration_Degree_Programs_Job_Aid.pdf" },
      { text: "CTUO Nursys RN License Verification Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/Nursys%20RN%20License%20Verification%20Job%20Aid.pdf" },
      { text: "CTUO DNP Admissions Process Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Online%20Advisor%20Performance%20Support%20Documents/DNP%20Admissions%20Process%20Job%20Aid.pdf" },
      { text: "CTUO ReEntry Nursing Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Guidebook%20Resources/ReEntry%20Nursing%20Job%20Aid.pdf" },
      { text: "CTU Application Reminders", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Online%20Advisor%20Performance%20Support%20Documents/REQ2026737%20Application%20Reminders%20POG%20CG%20NRSG%20INT%20Final.pdf" },
      { text: "CTUO Submitting a SAP Appeal Letter", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Guidebook%20Resources/Submitting_a_SAP_Letter_In_IMS.pdf" },
      { text: "COS Processing an Admissions Application Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/Performance%20Support%20Documents/GRD_Processing%20an%20Admissions%20Application.pdf" },
      { text: "CTUO/CD Processing an Admissions Application - Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Online%20Advisor%20Performance%20Support%20Documents/Processing%20an%20Admissions%20Application%20in%20APC_Version%201_Final.pdf" },
      { text: "Admissions Application Guide", href: "https://share.articulate.com/SZ-l7yBleVH37hb05SJRz" },
      { text: "Training Call Library - CTU", href: "file:///S:/CTU%20Admissions/Live%20Sites/Performance%20Support/index.html" },
      { text: "Training Call Library - Coding Dojo", href: "file:///S:/CTU%20Admissions/Live%20Sites/Performance%20Support/index.html" }
    ]
  },
  {
    id: "new-hire-homepage",
    title: "New Hire Homepage",
    links: [
      { text: "Unit 1: Welcome to CTU", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/01%20PW_Welcome%20to%20CTU.pdf" },
      { text: "Unit 2: Admissions Overview", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/02%20OL_PW_Admissions%20Overview.pdf" },
      { text: "Unit 3: Campus Presentation", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/03%20PW_OL_Campus%20Presentation.pdf" },
      { text: "Unit 4: Program & Product Knowledge", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/04%20OL_PW_Program%20and%20Product%20Knowledge.pdf" },
      { text: "Unit 5: Compliance", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/05%20OL_PW_Maintaining%20Compliant%20Culture.pdf" },
      { text: "Unit 6: Virtual Campus", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/06%20PW_OL_Introduction%20to%20the%20Virtual%20Campus.pdf" },
      { text: "Unit 7 (CTU Online): Intranet (Inquiry Management System)", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/07%20PW_Inquiry%20Management%20System.pdf" },
      { text: "Unit 7 (CTU COS/Ground): Admissions Desktop Management", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/07%20PW%20ADM_Final.pdf" },
      { text: "Unit 8: Do Not Call, EWC, NI, and Messaging Rules", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/08%20PW_DNCEWCNI+%20Messaging%20Rules.pdf" },
      { text: "Unit 9: Admissions Interview", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/09%20PW_OL_The%20Admissions%20Call.pdf" },
      { text: "Unit 10 (CTU Online): Admissions Application", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/10%20PW_Admissions%20Application.pdf" },
      { text: "Unit 10 (CTU COS/Ground): Admissions Application", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/10%20PW%20GRD%20Admissions%20Application.pdf" },
      { text: "Unit 11: Interview Fundamentals", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/11%20PW%20Interview%20Fundamental.pdf" },
      { text: "Unit 12: Presenting Information", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/12%20PW%20PresentingInfo_Final.pdf" },
      { text: "Unit 13: Student Preparation", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/13%20PW%20Unit%20Student%20Preparation.pdf" },
      { text: "Unit 14: Problem Solving", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/14%20PW%20Problem%20Solving.pdf" },
      { text: "Unit 15 (CTU Online): Technical Tools", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/15%20PW_Technical%20Tools.pdf" },
      { text: "Unit 15 (CTU COS/Ground): Technical Tools", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Workbook%20Participant%20Guide/15%20GRD%20PW%20Techical%20Tools.pdf" },
      { text: "Unit 1: Welcome to Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/01%20PW%20Welcome%20to%20Coding%20Dojo.pdf" },
      { text: "Unit 2: Admissions Overview - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/02%20PW%20CD%20Admissions%20Overview.pdf" },
      { text: "Unit 3: Exploring the Website - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/03%20PW%20Exploring%20the%20Website.pdf" },
      { text: "Unit 4: Program and Prod Knowledge - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/04%20PW%20Program%20and%20Prod%20Knowledge.pdf" },
      { text: "Unit 5: Compliance - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/05%20PW%20CD%20Compliance.pdf" },
      { text: "Unit 6: Virtual Campus - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/06%20PW%20Virtual%20Campus.pdf" },
      { text: "Unit 7: Admissions Interview Guide - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/07%20PW%20Admissions%20Interview%20Guide.pdf" },
      { text: "Unit 8: Dojo Intranet - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/08%20PW%20Dojo%20Intranet.pdf" },
      { text: "Unit 9: Admissions Application Process - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/09%20PW%20Admissions%20Application%20Process.pdf" },
      { text: "Unit 10: Student Preparation - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/10%20PW%20Student%20Preparation.pdf" },
      { text: "Unit 11: Problem Solving - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/11%20PW%20Problem%20Solving.pdf" },
      { text: "Unit 12: Technical Tools - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Coding%20Dojo%20New%20Hire%20Workbook%20PG/12%20PW%20Techical%20Tools.pdf" },
      { text: "CampusVue Guide - Supplemental Training", href: "https://share.articulate.com/c7lXa2MZ1fIw6h20AzdUC" },
      { text: "Commitment Grant Training Part 1: Self-Guided Commitment Grant Training", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Admissions%20Guidebooks/commitment-grant-self-guided-training/index.aspx" },
      { text: "Commitment Grant Training Part 2: Leader-Led Training", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Admissions%20Guidebooks/REQ2165228%20Comittment%20Grant%20Training%20v2.0%20Final.pptx" },
      { text: "Doctoral Admissions - Supplemental Training", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Admissions%20Guidebooks/Doctoral_Admissions_Supplemental_Training/index.aspx#/" },
      { text: "Live Chat Admissions - Supplemental Training", href: "https://share.articulate.com/WHfkFn1Txp9r2jMJLCcit" },
      { text: "Live Engage Systems - Supplemental Training", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Admissions%20Guidebooks/CTU%20Specialized%20Training%20-%20Live%20Engage.pptx" },
      { text: "Military Admissions - Supplemental Training", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Admissions%20Guidebooks/military-admissions-supplemental-training/index.aspx#/" },
      { text: "ReEntry Admissions - Supplemental Training", href: "https://share.articulate.com/AdSdkQHuxTGxd8QZFqlYO" },
      { text: "SAP Appeals - Supplemental Training", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Admissions%20Guidebooks/SPO_SAP_Appeals%20Process/index.aspx#/" },
      { text: "Military Knowledge Check - Supplemental Training", href: "https://forms.office.com/Pages/ResponsePage.aspx?id=MsVOFCEsMES_f0nwK4pn1_GakIpmGRFJuQekxSwF40lUNVVQTVFKQUhVQ1c0M0lQWjhSUjJSNzBRRS4u" },
      { text: "Gmail to Outlook Job Aid - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Gmail%20to%20Outlook%20Job%20Aid_Final.pdf" },
      { text: "Admissions Screen Setup - Coding Dojo", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/CD%20Admissions%20Screen%20Setup_Final.pdf" },
      { text: "New Hire FAQ", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/New%20Hire%20Internal%20FAQs_HR+Benefits.pdf" },
      { text: "Sentry Gatekeeper Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/training/Admissions%20Guidebooks/Sentry%20Gatekeeper%20Job%20Aid.pdf" },
      { text: "PEC Benefit Information", href: "https://livecareered.sharepoint.com/sites/ConnectEd/hr-and-policies/MyBenefits/Cigna.aspx" },
      { text: "CTU Program & Product Knowledge - PS Profile Cards", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Program%20%20Product%20Knowledge-%20Student%20Profile%20Cards.pdf" },
      { text: "CTU Doctoral Program & Product Knowledge - PS Profile Cards", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/CTU%20Doctoral%20Student%20Profile%20Cards_AA_Final.pdf" },
      { text: "Admissions Interview Role Play Profiles - CTU", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Role%20Play%20Final%20Role%20Play%20Cards_Final.pdf" },
      { text: "Admissions Advisor Screen Setup - CTU", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Main%20Screen%20Browser%20Set%20Up_final_2-2-18.pdf" },
      { text: "Admin Website: Quick Reference Guide", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/CTUO%20Admin%20Admin%20Site.pdf" },
      { text: "AVAYA & ContactPro Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Avaya%20and%20ContactPro%20Job%20Aid.pdf" },
      { text: "CT Suite Job Aid", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/CT%20Suite%20Job%20Aid%20Final%20_Agent.pdf" },
      { text: "Entering OT in IEX", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Entering%20OT%20in%20IEX.pdf" },
      { text: "Setting Up Your Voicemail", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Setting%20Up%20Your%20Voicemail.pdf" },
      { text: "Office Depot and GrubHub Order Form", href: "https://livecareered.sharepoint.com/sites/CTU/admissions/Admissions%20Forms/New%20Hire%20Resources/Office%20Depot_grubhub_Jobaid.pdf" }
    ]
  }
];
